// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseDB() {
  return window['go']['main']['App']['CloseDB']();
}

export function CreateDirectory(arg1) {
  return window['go']['main']['App']['CreateDirectory'](arg1);
}

export function CreateFile(arg1) {
  return window['go']['main']['App']['CreateFile'](arg1);
}

export function CreateNote(arg1) {
  return window['go']['main']['App']['CreateNote'](arg1);
}

export function CreateSandbox(arg1, arg2) {
  return window['go']['main']['App']['CreateSandbox'](arg1, arg2);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function DeletePath(arg1) {
  return window['go']['main']['App']['DeletePath'](arg1);
}

export function DeleteSandbox(arg1) {
  return window['go']['main']['App']['DeleteSandbox'](arg1);
}

export function DeleteSandboxFile(arg1, arg2) {
  return window['go']['main']['App']['DeleteSandboxFile'](arg1, arg2);
}

export function GetCrabRootDirectory() {
  return window['go']['main']['App']['GetCrabRootDirectory']();
}

export function GetGlobalSettings() {
  return window['go']['main']['App']['GetGlobalSettings']();
}

export function GetNotes() {
  return window['go']['main']['App']['GetNotes']();
}

export function GetPlaygroundDirectory() {
  return window['go']['main']['App']['GetPlaygroundDirectory']();
}

export function GetSandboxFiles(arg1) {
  return window['go']['main']['App']['GetSandboxFiles'](arg1);
}

export function GetSandboxes() {
  return window['go']['main']['App']['GetSandboxes']();
}

export function GetTemplates() {
  return window['go']['main']['App']['GetTemplates']();
}

export function GetTemplatesDirectory() {
  return window['go']['main']['App']['GetTemplatesDirectory']();
}

export function InitPlayground() {
  return window['go']['main']['App']['InitPlayground']();
}

export function InitTemplates() {
  return window['go']['main']['App']['InitTemplates']();
}

export function InitializeCrabFolder(arg1) {
  return window['go']['main']['App']['InitializeCrabFolder'](arg1);
}

export function IsDirectoryEmpty(arg1) {
  return window['go']['main']['App']['IsDirectoryEmpty'](arg1);
}

export function ListDirectory(arg1) {
  return window['go']['main']['App']['ListDirectory'](arg1);
}

export function OpenWorkspace(arg1) {
  return window['go']['main']['App']['OpenWorkspace'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RenamePath(arg1, arg2) {
  return window['go']['main']['App']['RenamePath'](arg1, arg2);
}

export function RenameSandbox(arg1, arg2) {
  return window['go']['main']['App']['RenameSandbox'](arg1, arg2);
}

export function RunCommand(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RunCommand'](arg1, arg2, arg3, arg4);
}

export function RunCommandWithEnv(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RunCommandWithEnv'](arg1, arg2, arg3, arg4, arg5);
}

export function RunSandbox(arg1, arg2) {
  return window['go']['main']['App']['RunSandbox'](arg1, arg2);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveGlobalSettings(arg1) {
  return window['go']['main']['App']['SaveGlobalSettings'](arg1);
}

export function SaveNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveNote'](arg1, arg2, arg3);
}

export function SaveSandboxConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveSandboxConfig'](arg1, arg2);
}

export function SaveSandboxFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveSandboxFile'](arg1, arg2, arg3, arg4);
}

export function SaveSandboxNotes(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSandboxNotes'](arg1, arg2, arg3);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function StopCommand(arg1) {
  return window['go']['main']['App']['StopCommand'](arg1);
}
