// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateSandbox(arg1, arg2) {
  return window['go']['main']['App']['ActivateSandbox'](arg1, arg2);
}

export function AddFileNote(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddFileNote'](arg1, arg2, arg3, arg4);
}

export function BackupWorkspace(arg1) {
  return window['go']['main']['App']['BackupWorkspace'](arg1);
}

export function CloseDB() {
  return window['go']['main']['App']['CloseDB']();
}

export function CreateSandbox(arg1, arg2) {
  return window['go']['main']['App']['CreateSandbox'](arg1, arg2);
}

export function CreateSandboxInFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSandboxInFolder'](arg1, arg2, arg3);
}

export function CreateWorkspace(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateWorkspace'](arg1, arg2, arg3, arg4);
}

export function DeleteFileNote(arg1) {
  return window['go']['main']['App']['DeleteFileNote'](arg1);
}

export function DeleteSandbox(arg1) {
  return window['go']['main']['App']['DeleteSandbox'](arg1);
}

export function DeleteSandboxFile(arg1, arg2) {
  return window['go']['main']['App']['DeleteSandboxFile'](arg1, arg2);
}

export function DeleteWorkspace(arg1) {
  return window['go']['main']['App']['DeleteWorkspace'](arg1);
}

export function ExportSandbox(arg1) {
  return window['go']['main']['App']['ExportSandbox'](arg1);
}

export function GetCrabRootDirectory() {
  return window['go']['main']['App']['GetCrabRootDirectory']();
}

export function GetFileNotes(arg1, arg2) {
  return window['go']['main']['App']['GetFileNotes'](arg1, arg2);
}

export function GetGlobalSettings() {
  return window['go']['main']['App']['GetGlobalSettings']();
}

export function GetPlaygroundDirectory() {
  return window['go']['main']['App']['GetPlaygroundDirectory']();
}

export function GetSandboxFiles(arg1) {
  return window['go']['main']['App']['GetSandboxFiles'](arg1);
}

export function GetSandboxes(arg1) {
  return window['go']['main']['App']['GetSandboxes'](arg1);
}

export function GetTemplates() {
  return window['go']['main']['App']['GetTemplates']();
}

export function GetTemplatesDirectory() {
  return window['go']['main']['App']['GetTemplatesDirectory']();
}

export function GetWorkspaceConfig(arg1) {
  return window['go']['main']['App']['GetWorkspaceConfig'](arg1);
}

export function GetWorkspaceConfigString(arg1) {
  return window['go']['main']['App']['GetWorkspaceConfigString'](arg1);
}

export function GetWorkspaceRuntimePath(arg1) {
  return window['go']['main']['App']['GetWorkspaceRuntimePath'](arg1);
}

export function GetWorkspaces() {
  return window['go']['main']['App']['GetWorkspaces']();
}

export function ImportSandbox(arg1, arg2) {
  return window['go']['main']['App']['ImportSandbox'](arg1, arg2);
}

export function InitPlayground() {
  return window['go']['main']['App']['InitPlayground']();
}

export function InitTemplates() {
  return window['go']['main']['App']['InitTemplates']();
}

export function InitializeCrabFolder(arg1) {
  return window['go']['main']['App']['InitializeCrabFolder'](arg1);
}

export function InitializeEnvironment(arg1) {
  return window['go']['main']['App']['InitializeEnvironment'](arg1);
}

export function IsDirectoryEmpty(arg1) {
  return window['go']['main']['App']['IsDirectoryEmpty'](arg1);
}

export function IsEnvironmentInitialized(arg1) {
  return window['go']['main']['App']['IsEnvironmentInitialized'](arg1);
}

export function MoveSandbox(arg1, arg2) {
  return window['go']['main']['App']['MoveSandbox'](arg1, arg2);
}

export function RenameSandbox(arg1, arg2) {
  return window['go']['main']['App']['RenameSandbox'](arg1, arg2);
}

export function ResetAndReinitializeEverything() {
  return window['go']['main']['App']['ResetAndReinitializeEverything']();
}

export function RestoreWorkspace(arg1) {
  return window['go']['main']['App']['RestoreWorkspace'](arg1);
}

export function RunCommand(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RunCommand'](arg1, arg2, arg3, arg4);
}

export function RunCommandWithEnv(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RunCommandWithEnv'](arg1, arg2, arg3, arg4, arg5);
}

export function RunSandbox(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunSandbox'](arg1, arg2, arg3);
}

export function SaveGlobalSettings(arg1) {
  return window['go']['main']['App']['SaveGlobalSettings'](arg1);
}

export function SaveSandboxFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveSandboxFile'](arg1, arg2, arg3, arg4);
}

export function SaveSandboxNotes(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSandboxNotes'](arg1, arg2, arg3);
}

export function SaveWorkspaceConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveWorkspaceConfig'](arg1, arg2);
}

export function StartTerminalSession(arg1, arg2) {
  return window['go']['main']['App']['StartTerminalSession'](arg1, arg2);
}

export function StopCommand(arg1) {
  return window['go']['main']['App']['StopCommand'](arg1);
}

export function UpdateFileNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateFileNote'](arg1, arg2, arg3);
}

export function WriteTerminalInput(arg1, arg2) {
  return window['go']['main']['App']['WriteTerminalInput'](arg1, arg2);
}
