// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ActivateSandbox(arg1:string,arg2:string):Promise<void>;

export function BackupWorkspace(arg1:string):Promise<string>;

export function CloseDB():Promise<void>;

export function CreateSandbox(arg1:string,arg2:string,arg3:string):Promise<main.Sandbox>;

export function CreateSandboxInFolder(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.Sandbox>;

export function CreateWorkspace(arg1:string,arg2:string,arg3:string):Promise<main.Workspace>;

export function DeleteSandbox(arg1:string):Promise<void>;

export function DeleteSandboxFile(arg1:string,arg2:string):Promise<void>;

export function DeleteWorkspace(arg1:string):Promise<void>;

export function ExportSandbox(arg1:string):Promise<string>;

export function GetCrabRootDirectory():Promise<string>;

export function GetGlobalSettings():Promise<main.GlobalSettings>;

export function GetPlaygroundDirectory():Promise<string>;

export function GetSandboxFiles(arg1:string):Promise<Array<main.SandboxFile>>;

export function GetSandboxes(arg1:string):Promise<Array<main.Sandbox>>;

export function GetTemplates():Promise<Array<main.TemplateSpec>>;

export function GetTemplatesDirectory():Promise<string>;

export function GetWorkspaceConfig(arg1:string):Promise<main.DeclarativeConfig>;

export function GetWorkspaceRuntimePath(arg1:string):Promise<string>;

export function GetWorkspaces():Promise<Array<main.Workspace>>;

export function ImportSandbox(arg1:string,arg2:string):Promise<main.Sandbox>;

export function InitPlayground():Promise<void>;

export function InitTemplates():Promise<void>;

export function InitializeCrabFolder(arg1:string):Promise<void>;

export function InitializeEnvironment(arg1:string):Promise<void>;

export function IsDirectoryEmpty(arg1:string):Promise<boolean>;

export function IsEnvironmentInitialized(arg1:string):Promise<boolean>;

export function MoveSandbox(arg1:string,arg2:string):Promise<void>;

export function RenameSandbox(arg1:string,arg2:string):Promise<void>;

export function RestoreWorkspace(arg1:string):Promise<main.Workspace>;

export function RunCommand(arg1:string,arg2:string,arg3:Array<string>,arg4:string):Promise<void>;

export function RunCommandWithEnv(arg1:string,arg2:string,arg3:Array<string>,arg4:string,arg5:Record<string, string>):Promise<void>;

export function RunSandbox(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveGlobalSettings(arg1:main.GlobalSettings):Promise<void>;

export function SaveSandboxFile(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function SaveSandboxNotes(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveWorkspaceConfig(arg1:string,arg2:string):Promise<void>;

export function StartTerminalSession(arg1:string,arg2:string):Promise<void>;

export function StopCommand(arg1:string):Promise<void>;

export function WriteTerminalInput(arg1:string,arg2:string):Promise<void>;
