// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseDB():Promise<void>;

export function CreateDirectory(arg1:string):Promise<void>;

export function CreateFile(arg1:string):Promise<void>;

export function CreateNote(arg1:string):Promise<main.Note>;

export function CreateSandbox(arg1:string,arg2:string):Promise<main.Sandbox>;

export function CreateSandboxInFolder(arg1:string,arg2:string,arg3:string):Promise<main.Sandbox>;

export function DeleteNote(arg1:string):Promise<void>;

export function DeletePath(arg1:string):Promise<void>;

export function DeleteSandbox(arg1:string):Promise<void>;

export function DeleteSandboxFile(arg1:string,arg2:string):Promise<void>;

export function GetCrabRootDirectory():Promise<string>;

export function GetGlobalSettings():Promise<main.GlobalSettings>;

export function GetNotes():Promise<Array<main.Note>>;

export function GetPlaygroundDirectory():Promise<string>;

export function GetSandboxDirectory(arg1:string):Promise<string>;

export function GetSandboxFiles(arg1:string):Promise<Array<main.SandboxFile>>;

export function GetSandboxes():Promise<Array<main.Sandbox>>;

export function GetTemplates():Promise<Array<main.TemplateSpec>>;

export function GetTemplatesDirectory():Promise<string>;

export function InitPlayground():Promise<void>;

export function InitTemplates():Promise<void>;

export function InitializeCrabFolder(arg1:string):Promise<void>;

export function InitializeEnvironment(arg1:string):Promise<void>;

export function IsDirectoryEmpty(arg1:string):Promise<boolean>;

export function IsEnvironmentInitialized(arg1:string):Promise<boolean>;

export function ListDirectory(arg1:string):Promise<Array<main.FileNode>>;

export function MoveSandbox(arg1:string,arg2:string):Promise<void>;

export function OpenWorkspace(arg1:string):Promise<main.WorkspaceInfo>;

export function ReadFile(arg1:string):Promise<string>;

export function RenamePath(arg1:string,arg2:string):Promise<void>;

export function RenameSandbox(arg1:string,arg2:string):Promise<void>;

export function RunCommand(arg1:string,arg2:string,arg3:Array<string>,arg4:string):Promise<void>;

export function RunCommandWithEnv(arg1:string,arg2:string,arg3:Array<string>,arg4:string,arg5:Record<string, string>):Promise<void>;

export function RunSandbox(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveGlobalSettings(arg1:main.GlobalSettings):Promise<void>;

export function SaveNote(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveSandboxConfig(arg1:string,arg2:string):Promise<void>;

export function SaveSandboxFile(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function SaveSandboxNotes(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SelectFolder():Promise<string>;

export function StartTerminalSession(arg1:string,arg2:string):Promise<void>;

export function StopCommand(arg1:string):Promise<void>;

export function WriteTerminalInput(arg1:string,arg2:string):Promise<void>;
