// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateDirectory(arg1:string):Promise<void>;

export function CreateFile(arg1:string):Promise<void>;

export function DeletePath(arg1:string):Promise<void>;

export function ListDirectory(arg1:string):Promise<Array<main.FileNode>>;

export function ReadFile(arg1:string):Promise<string>;

export function RenamePath(arg1:string,arg2:string):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SelectFolder():Promise<string>;
